language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise

before_script:
  - mysql -uroot -e "create database test;"
  - mysql -uroot -e "use test;"
  - mysql -uroot test < data/test_sample_ddl.sql
  - travis_retry composer install

script:
  - vendor/bin/phpunit --group sample